#!/usr/bin/env sh
# all initialization variables go here, then custom setup and whatnot

# ENVIRONMENT VARIABLES
LIB=$HOME/lib
SRC=$HOME/src
# EDITOR='emacsclient -a="" -nw'
EDITOR='vim'
GOPATH=$SRC/go
ERL_LIBS=$SRC
# RBENV_ROOT=/usr/local/var/rbenv
export LC_ALL="en_US.UTF-8"
export TERM=xterm-256color
export BROWSER=`which firefox` || `which chromium-browser`
export WORKON_HOME=$SRC/virtualenvs
export KEYID=0B78EF87

export EDITOR
export GOPATH
export ERL_LIBS
# export RBENV_ROOT
export ANDROID_SDK_ROOT

# PATH VARIABLE MODIFICATIONS

PATH=$LIB/bin:$PATH
PATH=$PATH:$SRC/elixir/bin

## for fixing Homebrew
PATH=/usr/local/bin:/usr/local/sbin:$PATH

# cabal executables
PATH=$HOME/.cabal/bin:$PATH

# GOPATH bin
PATH=$GOPATH/bin:$PATH

export PATH

alias em=$EDITOR
alias mux='tmuxinator'
alias ms='tmuxinator start'
alias mo='tmuxinator open'
if which hub > /dev/null
then
    alias git=hub
    alias g=hub
else
    alias g=git
fi
alias ga='git annex'
alias t='tmux'
alias ta='tmux attach'
alias tat='tmux attach -t'
alias sd="docker"
alias sdr="docker run -t -i"

alias cl='clear'
alias rel='source ~/lib/profile'
alias pm='python manage.py'
alias pms='python manage.py syncdb'
alias pmsh='python manage.py shell_plus'
alias pmdb='python manage.py dbshell'
alias pmr='python manage.py runserver'
alias pmrr='python manage.py runserver_plus'
alias pmm='python manage.py migrate --all'
alias py='ipython'

# OS specific aliases
if uname | grep -q "Darwin"
then
    source `which virtualenvwrapper.sh`
    alias inst='brew install'
    alias upd='brew update && brew upgrade'
    alias sea='brew search'
elif cat /etc/*-release | grep -q "Ubuntu"
then
    alias inst='sudo apt-get install'
    alias pa='apt-get'
    alias upd='sudo apt-get update && sudo apt-get upgrade'
    alias sea='aptitude search'
else
    source `which virtualenvwrapper.sh`
    alias inst='sudo packer -S'
    alias pa='packer'
    alias upd='packer -Syu'
    alias sea='packer -Ss'
fi

# jmp commands
export MARKPATH=$HOME/marks
function jmp {
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark {
    mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark {
    rm -i "$MARKPATH/$1"
}
function marks {
    ls -l "$MARKPATH" | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
}

function _completemarks {
  reply=($(ls $MARKPATH))
}

compctl -K _completemarks jmp
compctl -K _completemarks unmark


# jump to editing of common files
alias emd="$EDITOR ~/.emacs.d/init.el"
alias emlp="$EDITOR ~/lib/profile"
alias emt="$EDITOR ~/notes/todo.org"
alias emgc="$EDITOR ~/.gitconfig"
