#!/bin/sh
# all initialization variables go here, then custom setup and whatnot

# setup for tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator


# ENVIRONMENT VARIABLES
PLAN9=/Users/aronasorman/src/plan9port export PLAN9
LIB=$HOME/lib
SRC=$HOME/src
EMU="-r$SRC/inferno -g1250x750 -c1" export EMU
EDITOR='emacsclient -a="" -nw'
#EDITOR='vim'
GOPATH=$HOME/go
ERL_LIBS=$SRC
# RBENV_ROOT=/usr/local/var/rbenv
ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
export LC_ALL="en_US.UTF-8"
export TERM=xterm-256color
export WORKON_HOME=$SRC/virtualenvs
source /usr/bin/virtualenvwrapper.sh

export EDITOR
export GOPATH
export ERL_LIBS
# export RBENV_ROOT
export ANDROID_SDK_ROOT

# PATH VARIABLE MODIFICATIONS

## adding some plan9 related utilities
PATH=$LIB/bin:$PATH
PATH=/usr/inferno/MacOSX/386/bin:$PATH
PATH=$SRC/acme-utils:$PATH
PATH=$PATH:$PLAN9/bin

## for fixing Homebrew
PATH=/usr/local/bin:/usr/local/sbin:$PATH

# cabal executables
PATH=$HOME/.cabal/bin:$PATH

# texlive
PATH=/usr/local/texlive/2012/bin/universal-darwin:$PATH

# GOPATH bin
PATH=$GOPATH/bin:$PATH

export PATH

alias em=$EDITOR
alias mux='tmuxinator'
alias ms='tmuxinator start'
alias mo='tmuxinator open'
alias g=git
alias ga='git annex'
alias t='tmux'
alias ta='tmux attach'
alias tat='tmux attach -t'

alias cl='clear'
alias rel='source ~/lib/profile'
alias pm='python manage.py'
alias pms='python manage.py syncdb'
alias pmsh='python manage.py shell_plus'
alias pmdb='python manage.py dbshell'
alias pmr='python manage.py runserver_plus'
alias pmm='python manage.py migrate --all'
alias py='python'

# OS specific aliases
if cat /etc/*-release | grep -q "Ubuntu"
then
    echo 'ubuntu detected, placing ubuntu-specific aliases'
    alias inst='sudo apt-get install'
    alias pa='apt-get'
    alias upd='sudo apt-get update && sudo apt-get upgrade'
    alias sea='aptitude search'
else
    echo 'arch linux assumed, placing arch spefic stuff'
    alias inst='sudo pacaur -S'
    alias pa='pacaur'
    alias upd='pacaur -Syu'
    alias sea='pacaur -Ss'
fi

# jump to editing of common files
alias emd="$EDITOR ~/.emacs.d/init.el"
alias emlp="$EDITOR ~/lib/profile"
alias emt="$EDITOR ~/notes/todo.org"
alias emgc="$EDITOR ~/.gitconfig"
